// Technology category configurations with colors and gradients
export const techCategories = {
  dotnet: {
    name: '.NET',
    color: '#512BD4',
    gradient: 'from-purple-600 via-purple-500 to-blue-600',
    bgGradient: 'from-purple-50 to-blue-50',
    darkBgGradient: 'from-purple-900/20 to-blue-900/20',
    icon: '⚡',
    pattern: 'dots',
  },
  csharp: {
    name: 'C#',
    color: '#239120',
    gradient: 'from-green-600 via-green-500 to-purple-600',
    bgGradient: 'from-green-50 to-purple-50',
    darkBgGradient: 'from-green-900/20 to-purple-900/20',
    icon: '#️⃣',
    pattern: 'grid',
  },
  react: {
    name: 'React',
    color: '#61DAFB',
    gradient: 'from-cyan-400 via-cyan-300 to-blue-500',
    bgGradient: 'from-cyan-50 to-blue-50',
    darkBgGradient: 'from-cyan-900/20 to-blue-900/20',
    icon: '⚛️',
    pattern: 'circles',
  },
  nextjs: {
    name: 'Next.js',
    color: '#000000',
    gradient: 'from-gray-900 via-gray-800 to-gray-700',
    bgGradient: 'from-gray-50 to-gray-100',
    darkBgGradient: 'from-gray-800/20 to-gray-900/20',
    icon: '▲',
    pattern: 'triangles',
  },
  javascript: {
    name: 'JavaScript',
    color: '#F7DF1E',
    gradient: 'from-yellow-400 via-yellow-300 to-orange-500',
    bgGradient: 'from-yellow-50 to-orange-50',
    darkBgGradient: 'from-yellow-900/20 to-orange-900/20',
    icon: 'JS',
    pattern: 'waves',
  },
  typescript: {
    name: 'TypeScript',
    color: '#3178C6',
    gradient: 'from-blue-600 via-blue-500 to-blue-800',
    bgGradient: 'from-blue-50 to-blue-100',
    darkBgGradient: 'from-blue-900/20 to-blue-800/20',
    icon: '📘',
    pattern: 'squares',
  },
  aws: {
    name: 'AWS',
    color: '#FF9900',
    gradient: 'from-orange-500 via-orange-400 to-yellow-600',
    bgGradient: 'from-orange-50 to-yellow-50',
    darkBgGradient: 'from-orange-900/20 to-yellow-900/20',
    icon: '☁️',
    pattern: 'clouds',
  },
  azure: {
    name: 'Azure',
    color: '#0078D4',
    gradient: 'from-blue-600 via-blue-500 to-cyan-500',
    bgGradient: 'from-blue-50 to-cyan-50',
    darkBgGradient: 'from-blue-900/20 to-cyan-900/20',
    icon: '☁️',
    pattern: 'hexagons',
  },
  angular: {
    name: 'Angular',
    color: '#DD0031',
    gradient: 'from-red-600 via-red-500 to-pink-600',
    bgGradient: 'from-red-50 to-pink-50',
    darkBgGradient: 'from-red-900/20 to-pink-900/20',
    icon: '🅰️',
    pattern: 'shields',
  },
  docker: {
    name: 'Docker',
    color: '#2496ED',
    gradient: 'from-blue-500 via-blue-400 to-cyan-400',
    bgGradient: 'from-blue-50 to-cyan-50',
    darkBgGradient: 'from-blue-900/20 to-cyan-900/20',
    icon: '🐳',
    pattern: 'containers',
  },
  kubernetes: {
    name: 'Kubernetes',
    color: '#326CE5',
    gradient: 'from-blue-600 via-blue-500 to-indigo-600',
    bgGradient: 'from-blue-50 to-indigo-50',
    darkBgGradient: 'from-blue-900/20 to-indigo-900/20',
    icon: '☸️',
    pattern: 'hexagons',
  },
  sql: {
    name: 'SQL',
    color: '#CC2927',
    gradient: 'from-red-600 via-red-500 to-orange-600',
    bgGradient: 'from-red-50 to-orange-50',
    darkBgGradient: 'from-red-900/20 to-orange-900/20',
    icon: '🗄️',
    pattern: 'database',
  },
  postgresql: {
    name: 'PostgreSQL',
    color: '#336791',
    gradient: 'from-blue-700 via-blue-600 to-blue-900',
    bgGradient: 'from-blue-50 to-blue-100',
    darkBgGradient: 'from-blue-900/20 to-blue-950/20',
    icon: '🐘',
    pattern: 'database',
  },
  mongodb: {
    name: 'MongoDB',
    color: '#47A248',
    gradient: 'from-green-600 via-green-500 to-green-800',
    bgGradient: 'from-green-50 to-green-100',
    darkBgGradient: 'from-green-900/20 to-green-950/20',
    icon: '🍃',
    pattern: 'leaves',
  },
  entityframework: {
    name: 'Entity Framework',
    color: '#512BD4',
    gradient: 'from-purple-700 via-purple-600 to-indigo-700',
    bgGradient: 'from-purple-50 to-indigo-50',
    darkBgGradient: 'from-purple-900/20 to-indigo-900/20',
    icon: '🔗',
    pattern: 'links',
  },
  general: {
    name: 'General',
    color: '#6B7280',
    gradient: 'from-gray-600 to-gray-800',
    bgGradient: 'from-gray-50 to-gray-100',
    darkBgGradient: 'from-gray-800/20 to-gray-900/20',
    icon: '📝',
    pattern: 'dots',
  },
};

export type TechCategory = keyof typeof techCategories;

export function getTechConfig(language: string) {
  const normalizedLanguage = language.toLowerCase().replace(/[.\s-]/g, '');
  return techCategories[normalizedLanguage as TechCategory] || techCategories.general;
}
