// Technology category configurations with colors and gradients
export const techCategories = {
  dotnet: {
    name: '.NET',
    color: '#512BD4',
    gradient: 'from-[#512BD4] to-[#6d46f5]',
    bgGradient: 'from-purple-50 to-blue-50',
    darkBgGradient: 'from-purple-900/20 to-blue-900/20',
    icon: '⚡',
    pattern: 'dots',
  },
  csharp: {
    name: 'C#',
    color: '#239120',
    gradient: 'from-[#239120] to-[#2ecc71]',
    bgGradient: 'from-green-50 to-purple-50',
    darkBgGradient: 'from-green-900/20 to-purple-900/20',
    icon: '🎯',
    pattern: 'grid',
  },
  react: {
    name: 'React',
    color: '#61DAFB',
    gradient: 'from-[#61DAFB] to-[#00a8cc]',
    bgGradient: 'from-cyan-50 to-blue-50',
    darkBgGradient: 'from-cyan-900/20 to-blue-900/20',
    icon: '⚛️',
    pattern: 'circles',
  },
  nextjs: {
    name: 'Next.js',
    color: '#000000',
    gradient: 'from-slate-900 to-slate-700',
    bgGradient: 'from-gray-50 to-gray-100',
    darkBgGradient: 'from-gray-800/20 to-gray-900/20',
    icon: '▲',
    pattern: 'triangles',
  },
  javascript: {
    name: 'JavaScript',
    color: '#F7DF1E',
    gradient: 'from-[#F7DF1E] to-[#f39c12]',
    bgGradient: 'from-yellow-50 to-orange-50',
    darkBgGradient: 'from-yellow-900/20 to-orange-900/20',
    icon: 'JS',
    pattern: 'waves',
  },
  typescript: {
    name: 'TypeScript',
    color: '#3178C6',
    gradient: 'from-[#3178C6] to-[#2980b9]',
    bgGradient: 'from-blue-50 to-blue-100',
    darkBgGradient: 'from-blue-900/20 to-blue-800/20',
    icon: '📘',
    pattern: 'squares',
  },
  aws: {
    name: 'AWS',
    color: '#FF9900',
    gradient: 'from-[#FF9900] to-[#f39c12]',
    bgGradient: 'from-orange-50 to-yellow-50',
    darkBgGradient: 'from-orange-900/20 to-yellow-900/20',
    icon: '☁️',
    pattern: 'clouds',
  },
  azure: {
    name: 'Azure',
    color: '#0078D4',
    gradient: 'from-[#0078D4] to-[#00b4db]',
    bgGradient: 'from-blue-50 to-cyan-50',
    darkBgGradient: 'from-blue-900/20 to-cyan-900/20',
    icon: '☁️',
    pattern: 'hexagons',
  },
  angular: {
    name: 'Angular',
    color: '#DD0031',
    gradient: 'from-[#DD0031] to-[#e91e63]',
    bgGradient: 'from-red-50 to-pink-50',
    darkBgGradient: 'from-red-900/20 to-pink-900/20',
    icon: '🅰️',
    pattern: 'shields',
  },
  docker: {
    name: 'Docker',
    color: '#2496ED',
    gradient: 'from-[#2496ED] to-[#00bcd4]',
    bgGradient: 'from-blue-50 to-cyan-50',
    darkBgGradient: 'from-blue-900/20 to-cyan-900/20',
    icon: '🐳',
    pattern: 'containers',
  },
  kubernetes: {
    name: 'Kubernetes',
    color: '#326CE5',
    gradient: 'from-[#326CE5] to-[#1565c0]',
    bgGradient: 'from-blue-50 to-indigo-50',
    darkBgGradient: 'from-blue-900/20 to-indigo-900/20',
    icon: '☸️',
    pattern: 'hexagons',
  },
  sql: {
    name: 'SQL',
    color: '#CC2927',
    gradient: 'from-[#CC2927] to-[#e74c3c]',
    bgGradient: 'from-red-50 to-orange-50',
    darkBgGradient: 'from-red-900/20 to-orange-900/20',
    icon: '🗄️',
    pattern: 'database',
  },
  postgresql: {
    name: 'PostgreSQL',
    color: '#336791',
    gradient: 'from-[#336791] to-[#2c3e50]',
    bgGradient: 'from-blue-50 to-blue-100',
    darkBgGradient: 'from-blue-900/20 to-blue-950/20',
    icon: '🐘',
    pattern: 'database',
  },
  mongodb: {
    name: 'MongoDB',
    color: '#47A248',
    gradient: 'from-[#47A248] to-[#1e824c]',
    bgGradient: 'from-green-50 to-green-100',
    darkBgGradient: 'from-green-900/20 to-green-950/20',
    icon: '🍃',
    pattern: 'leaves',
  },
  entityframework: {
    name: 'Entity Framework',
    color: '#512BD4',
    gradient: 'from-[#512BD4] to-[#4b12ab]',
    bgGradient: 'from-purple-50 to-indigo-50',
    darkBgGradient: 'from-purple-900/20 to-indigo-900/20',
    icon: '🔗',
    pattern: 'links',
  },
  general: {
    name: 'General',
    color: '#6B7280',
    gradient: 'from-slate-700 to-slate-500',
    bgGradient: 'from-gray-50 to-gray-100',
    darkBgGradient: 'from-gray-800/20 to-gray-900/20',
    icon: '📝',
    pattern: 'dots',
  },
};

export type TechCategory = keyof typeof techCategories;

export function getTechConfig(language: string) {
  const normalizedLanguage = language.toLowerCase().replace(/[.\s-]/g, '');
  return techCategories[normalizedLanguage as TechCategory] || techCategories.general;
}
